all: libbs2b.tar.gz alsamodularsynth.tar.gz sunvox.tar.gz crack-attack.tar.gz libdatrie.tar.gz libthai.tar.gz

sunvox.tar.gz: sunvox
	tar czvf sunvox.tar.gz sunvox/{README,doinst.sh,slack-desc,sunvox.SlackBuild,sunvox.desktop,sunvox.info,sunvox.png}

alsamodularsynth.tar.gz: alsamodularsynth
	tar czvf alsamodularsynth.tar.gz alsamodularsynth/{README,alsamodularsynth.SlackBuild,alsamodularsynth.info,slack-desc,configure.patch}

libbs2b.tar.gz: libbs2b
	tar czvf libbs2b.tar.gz libbs2b/{README,libbs2b.SlackBuild,libbs2b.info,slack-desc}

crack-attack.tar.gz: crack-attack
	tar czvf crack-attack.tar.gz crack-attack/{README,crack-attack.SlackBuild,crack-attack.info,slack-desc,includes.patch}

libdatrie.tar.gz: libdatrie
	tar czvf libdatrie.tar.gz libdatrie/{README,libdatrie.SlackBuild,libdatrie.info,slack-desc}

libthai.tar.gz: libthai
	tar czvf libthai.tar.gz libthai/{README,libthai.SlackBuild,libthai.info,slack-desc}
