all: libbs2b.tar.gz alsamodularsynth.tar.gz sunvox.tar.gz

sunvox.tar.gz: sunvox
	tar czvf sunvox.tar.gz sunvox/{README,doinst.sh,slack-desc,sunvox.SlackBuild,sunvox.desktop,sunvox.info,sunvox.png}

alsamodularsynth.tar.gz: alsamodularsynth
	tar czvf alsamodularsynth.tar.gz alsamodularsynth/{README,alsamodularsynth.SlackBuild,alsamodularsynth.info,slack-desc,configure.patch}


libbs2b.tar.gz: libbs2b
	tar czvf libbs2b.tar.gz libbs2b/{README,libbs2b.SlackBuild,libbs2b.info,slack-desc}

